name: "File presence check"
on: [pull_request, push]

jobs:
  file_presence:
    runs-on: ubuntu-latest
    steps:
    - uses: JJ/files-present-action@releases/v1
    - name: "Check for a set of files"
      files:
        - package.json
        - LICENSE
        - README.md
