name: "File presence check"
on: [pull_request, push]

jobs:
  file_presence:
    runs-on: ubuntu-latest
    steps:
      - name: "Check file presence"
        uses: JJ/files-present-action@releases/v1
        with:
          files:
            - package.json
            - LICENSE
            - README.md
